# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
