# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20160911_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='list',
            new_name='wishlist',
        ),
    ]
